### ISSUE TITLE
extension requires a newer version

### ISSUE THREAD

**Issue by RafaelSz** [zaggino/brackets-coffeelint#1]
This extension requires a newer version of Brackets.

BUT I have the newest version:

Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
build timestamp: Sun Feb 22 2015 22:34:56 GMT-0800

**Comment by zaggino** [comment]
It says in the description that this must be installed using https://github.com/zaggino/brackets-npm-registry (in-built registry won't work)

**Comment by RafaelSz** [comment]
All right, but it does not says "this MUST be installed", that is why I did not even try to do so, because of false version requirement message :)

**Comment by zaggino** [comment]
Message says `Use 'brackets-npm-registry' extension to install.`, so you should use it :) In-built registry doesn't support installing with npm dependencies and this linter uses latest npm versions.

**Comment by zaggino** [comment]
I've changed message to `"Ignore version error and use 'brackets-npm-registry' to install."` ;)

**Comment by RafaelSz** [comment]
Great, I think now the messages are less confusing, especially for all new Brackets users, like I am :)

**Comment by zaggino** [comment]
:+1:

**Comment by zaggino** [comment]
Ok, let me know if `brackets-npm-registry` did/didn't work for you.

**Comment by RafaelSz** [comment]
All works fine :)
