### ISSUE TITLE
does not support "Lint Files on Save"

### ISSUE THREAD

**Issue by amitkeret** [zaggino/brackets-coffeelint#2]
Hello,

I've been using this extension, and it works well when opening new files.
However, when saving files after changes, the linter does not update its output. This is even though I've turned on "View -> Lint Files on Save" in the main menu.

Thanks

**Comment by zaggino** [comment]
Hi, something must be wrong with your Brackets installation or configuration. I use this extension on a daily basis and `Lint Files on Save` works properly as it should. Can you get me a list of extensions, that you have installed? Thanks

**Comment by amitkeret** [comment]
```
$ ls -l ~/.config/Brackets/extensions/user/
brackets-coffeelint
brackets-compare
brackets-editorconfig
brackets-integrated-development
brackets-npm-registry
camden.csslint
camden.htmlhint
camden.jshint
garthdb.brackets-stylus
giovannicalo.brackets-coffeescript
globexdesigns.brackets-jscs
gruehle.markdown-preview
hirse.beautify
ivogabe.icons
jade
jshint.configurator
phoenix.brackets.phplinter
zaggino.brackets-git
```

here's my configuration for linting in `brackets.json`:

```
  "linting.collapsed": true,
  "linting.enabled": true,
  "language": {
    "javascript": {
        "linting.prefer": [
            "JSHint",
            "JSCS"
        ],
        "linting.usePreferredOnly": true
    }
  },
```

I noticed there's nothing in `brackets.json` about linting on save, should there be?

**Comment by zaggino** [comment]
No, you shouldn't need to add anything there. You don't have any errors in the console at all? (F12 to open or Cmd+Opt+I on Mac)

**Comment by amitkeret** [comment]
There are some warning, no errors.

A lot of these:

```
Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
```

And one of this:

```
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
```

**Comment by zaggino** [comment]
I've tried this on three separate computers now and it works fine on all of them. Sorry, but I've got no idea what might be wrong with yours. Have you tried using my `brackets-eslint` ? Its internals are pretty much the same as the ones in `brackets-coffeelint` - it might be worth checking out, if it has the same problem.

**Comment by amitkeret** [comment]
@zaggino 
Thanks for all your testing.

After your comment, I tried re-installing Brackets, and later re-installing all my extensions in sequence.
I found that the culprit is [brackets-phplinter](https://github.com/phoenix3008/brackets-phplinter). I have posted [an issue](https://github.com/phoenix3008/brackets-phplinter/issues/3) on the subject.

Thanks again, now it works and I love it!
